# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-08-19 15:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0009_auto_20190816_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='roles',
        ),
        migrations.DeleteModel(
            name='Userinfo',
        ),
    ]
